// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqqW1Bt6OiItreR6MgCgz10gIo1QChVc',
    appId: '1:22171453441:android:d2bf1d5aade8b6464d5800',
    messagingSenderId: '22171453441',
    projectId: 'optiway',
    storageBucket: 'optiway.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUt6fQ5ZtzZsYIrjwgmiS4mDoUKQ9Y4gI',
    appId: '1:22171453441:ios:d146945b749309c54d5800',
    messagingSenderId: '22171453441',
    projectId: 'optiway',
    storageBucket: 'optiway.appspot.com',
    iosBundleId: 'com.example.optiway',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2_mi_dVWi-F3ui9fu4mUBPKXQFl5BK8',
    appId: '1:22171453441:web:8edad4af851143e74d5800',
    messagingSenderId: '22171453441',
    projectId: 'optiway',
    authDomain: 'optiway.firebaseapp.com',
    storageBucket: 'optiway.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUt6fQ5ZtzZsYIrjwgmiS4mDoUKQ9Y4gI',
    appId: '1:22171453441:ios:d146945b749309c54d5800',
    messagingSenderId: '22171453441',
    projectId: 'optiway',
    storageBucket: 'optiway.appspot.com',
    iosBundleId: 'com.example.optiway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC2_mi_dVWi-F3ui9fu4mUBPKXQFl5BK8',
    appId: '1:22171453441:web:352b20eeda118dde4d5800',
    messagingSenderId: '22171453441',
    projectId: 'optiway',
    authDomain: 'optiway.firebaseapp.com',
    storageBucket: 'optiway.appspot.com',
  );

}