// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0op6zEayC48tsMjFMhW0C7rst5c75C_o',
    appId: '1:716196782770:android:82ae6db8fd689d7ceb9fab',
    messagingSenderId: '716196782770',
    projectId: 'optiway-9e907',
    storageBucket: 'optiway-9e907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQXZ-HA_DxPwMnv_IWVPBpZQ8g6_5FiuI',
    appId: '1:716196782770:ios:9831e5c488516380eb9fab',
    messagingSenderId: '716196782770',
    projectId: 'optiway-9e907',
    storageBucket: 'optiway-9e907.appspot.com',
    iosBundleId: 'com.example.optiway',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1LVc66GCg1tGzsfBJ_NAd7jG-ku12EM',
    appId: '1:716196782770:web:3174a7b4a7382ba4eb9fab',
    messagingSenderId: '716196782770',
    projectId: 'optiway-9e907',
    authDomain: 'optiway-9e907.firebaseapp.com',
    storageBucket: 'optiway-9e907.appspot.com',
    measurementId: 'G-M5FY7MKDCP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQXZ-HA_DxPwMnv_IWVPBpZQ8g6_5FiuI',
    appId: '1:716196782770:ios:9831e5c488516380eb9fab',
    messagingSenderId: '716196782770',
    projectId: 'optiway-9e907',
    storageBucket: 'optiway-9e907.appspot.com',
    iosBundleId: 'com.example.optiway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ1LVc66GCg1tGzsfBJ_NAd7jG-ku12EM',
    appId: '1:716196782770:web:da6672deac56ed4beb9fab',
    messagingSenderId: '716196782770',
    projectId: 'optiway-9e907',
    authDomain: 'optiway-9e907.firebaseapp.com',
    storageBucket: 'optiway-9e907.appspot.com',
    measurementId: 'G-E8SXVDYR31',
  );

}